### ISSUE TITLE
Supervised mode Assertion failed

### ISSUE THREAD

**Issue by KangchengHou** [ekmolloy/ProPCA#1]
Hi,

Thanks for making this great tool.

I am encountering the following error:

```
${SCOPE_BIN} \
    -g 1kg \
    -freq 1kg_freq.frq.strat \
    -o supervised_

Running on Dataset of 64462 SNPs and 3202 Individuals
Performing latent subspace estimation
Latent subspace esimation completed after 12 iterations
Solving for Q using provided frequencies
Assertion failed: (row >= 0 && row < rows() && col >= 0 && col < cols()), function operator(), file scope_replicate/SCOPE/include/Eigen/src/Core/DenseCoeffsBase.h, line 365.
[1]    55338 abort      ${SCOPE_BIN} -g 1kg -freq 1kg_freq.frq.strat -o supervised_
```

Here I am using infer ancestry proportion of 1kg samples using 1kg derived frequencies. And I can replicate this in both CentOS 7 and MACOS.

Attached is the data I used to run the SCOPE
https://www.dropbox.com/s/s91tnokmhj8m1us/scope_replicate.zip?dl=0

Could you advise what could be checked? Thanks

**Comment by alecmchiu** [comment]
Hi Kangcheng,

Thanks for providing the data to replicate the error. 

We currently don't perform a check to see how many populations are the in frequency file, so it was trying to match the default of 5 populations to the 4 populations from the frequency file.

Adding the `-k 4` option fixes the error.

```
${SCOPE_BIN} \
    -g 1kg \
    -k 4 \
    -freq 1kg_freq.frq.strat \
    -o supervised_
```

We'll add a check for the supplied number of populations for the frequency file.

**Comment by KangchengHou** [comment]
Thank you Alec! I confirm it works on my end now. 

Another question: can SCOPE handle missing genotype? If my data has missing genotype, what do you recommend to cope with that?

Thanks in advance

**Comment by alecmchiu** [comment]
Yes, SCOPE can handle missing genotypes. It fills in missing values from random values drawn from a binomial using the overall SNP frequency.
