### ISSUE TITLE
Cross Validation

### ISSUE THREAD

**Issue by Lindo007** [ekmolloy/ProPCA#2]
Hello,

Is there a way to get a cross validation value to determine the best K?

Thank you,

John

**Comment by alecmchiu** [comment]
Hi John,

There's currently no built-in method to determine the best value for the number of latent population (K).

There are a couple of post-hoc methods that can be used to determine the best number of latent populations such as those using likelihoods and information criterion (e.g. AIC, BIC).

Here is a messy, but quick script in R to calculate some of these quantities on our provided example data:

```
#!/bin/env Rscript

library(genio)
library(data.table)

P <- fread("unsupervised_example_1k_Phat.txt",data.table=F)
Q <- fread("unsupervised_example_1k_Qhat.txt",data.table=F)
F_mat <- as.matrix(P) %*% as.matrix(Q)

geno <- read_plink("../../source_files/example_1k")$X

m <- dim(geno)[1]
n <- dim(geno)[2]

# Likelihood and log-likelihood
likelihood <- prod(sapply(1:m,function(x){dbinom(geno[x,],2,F_mat[x,])}))
log_likelihood <- sum(log(sapply(1:m,function(x){dbinom(geno[x,],2,F_mat[x,])})))

k <- prod(dim(P),dim(Q)) # number of parameters estimated

# AIC and BIC
aic <- 2*k - 2*log_likelihood
bic <- k*log(n) - 2*log_likelihood
```

**Comment by Lindo007** [comment]
Thank you very much!
