### ISSUE TITLE
Order of individuals

### ISSUE THREAD

**Issue by sophiekj** [ekmolloy/ProPCA#3]
Hello,

Thank you for sharing this program!

I could not find in your Github description of the output Qhat file with the ancestry proportions whether or not the order of sample/individual names is conserved from the input Plink files. 

I read your publication, which states that "For our PSD simulations, we performed hierarchical clustering with complete linkage on a Euclidean distance matrix calculated from the true admixture proportion matrix (Q) to obtain the order of samples".

Does this mean there is no true way of retaining the sample names order, and it must be inferred mathematically? How exactly should this be done, if so?

Thank you,
Sophie

**Comment by alecmchiu** [comment]
Hi Sophie,

Thanks for your interest in our software.

The order of sample/individuals is indeed conserved from the PLINK files (i.e. same order as FAM file).

The statement you were referring to is for aligning the populations from different unsupervised runs from SCOPE or other methods.

Best,

Alec

**Comment by sophiekj** [comment]
Ah wonderful, thank you! I appreciate the clarification.
